### ISSUE TITLE
Support for remote web socket server

### ISSUE THREAD

**Issue by erez-work** [davidje13/superwstest#1]
Currently lib only supports local express server.

It's simple to support remote server as well by adding this to `superwstest.js` default export function:
``` js
  if (typeof server === 'string') {
    const obj = request(server);
    obj.ws = (path, ...args) => wsRequest(server + path, ...args);
    return obj;
  }
```

**Comment by davidje13** [comment]
I merged your changes, added documentation and tests, and released this in version 1.1.0

Give it a go and let me know if it works for you.

Thanks for the contribution!
