### ISSUE TITLE
Add support for Express apps

### ISSUE THREAD

**Issue by brunogirin** [davidje13/superwstest#11]
In order to make the API more closely aligned with supertest, add support for the Express apps. `supertest` makes it possible to write:

```javascript
await request(app).get(...)
```

When doing this, `supertest` starts the server before running the tests and closes it at the end. `superwstest` currently requires this to be done externally in `beforeEach` and `afterAll` blocks. Mimicking what `supertest` does would make it easier for people who come from `supertest` to pick up `superwstest`.

**Comment by davidje13** [comment]
I recall looking in to this back when I was writing the library, and in the end decided the more explicit form is safer. If I recall correctly, supertest itself has a subtle bug if you pass an express app in and rely on it starting & stopping the server for you (I'll see if I can find the issue for it. Vaguely remember something about a race condition causing tests to occasionally fail…)

**Comment by davidje13** [comment]
Ah; found it (easy to find because I raised it!): https://github.com/visionmedia/supertest/issues/566

See also the linked issues for that; at least at the time (and maybe still?), supertest never closed servers started this way, so as your tests run you will gradually build up more and more servers listening on different ports! It's a pity that style is the one they push in the readme because it's really quite problematic!

**Comment by davidje13** [comment]
I added a [section to the readme](https://github.com/davidje13/superwstest#why-isnt-requestapp-supported) to explain this decision in detail and updated the error thrown by the library to include a link to it.

So for now I'm going to close this as won't-fix. I think at the very least, adding this feature would depend on https://github.com/visionmedia/supertest/issues/566 being fixed first, but even with that fixed, it would need to be possible to reliably know when the test has finished to avoid leaving the test runner hanging (requiring the user to add an `afterEach` for this would presumably be no better than the current situation).

Feel free to re-open if you have any suggestions on how to support this safely.
