### ISSUE TITLE
Error thrown when following the API docs example

### ISSUE THREAD

**Issue by anthonyorona** [davidje13/superwstest#14]
I am using:

    "supertest": "^6.2.2",
    "superwstest": "^2.0.1"

And I am using the Node ws library, following a recommended pattern to wrap the http server so that it is shared by the ws server.
My server uses a session cookie that requires me to run requests against non-WebSocket endpoints to login and logout.

https://www.npmjs.com/package/ws#multiple-servers-sharing-a-single-https-server

Here is my example test:
```
const server = wrapServer(createServer(app));

describe('WebSocket Tests', () => {
  describe('Standard Tests', () => {
    beforeEach(async () => {
      try {
        await server.listen(0, 'localhost');
        await request(server).post('/auth/login').send({ email: 'email', password: 'password' }).expect(200);
      } catch (e) {
        console.log(e);
      }
    });

    it('It communicates over HTTP', async () => {
      await request(server)
        .ws(getSocketURL())
        .sendJson({ messageType: WSS.REQUEST })
        .expectJson()
        .close()
        .expectClosed();
    });

    afterEach(async () => {
      await request(server).get('/auth/logout').expect(200);
      await server.close();
    });
  });
});

```
Based on the API docs, I believe this should run, but instead I get this error:

```
Error: Server must be listening:
beforeEach((done) => server.listen(0, 'localhost', done));
afterEach((done) => server.close(done));

supertest's request(app) syntax is not supported (find out more: https://github.com/davidje13/superwstest#why-isnt-requestapp-supported)
    at getHttpBase (node_modules/superwstest/build/superwstest.js:443:11)
    at request (node_modules/superwstest/build/superwstest.js:470:22)
    at Context.<anonymous> (test/websocket.test.js:40:13)
```

This syntax is an example in the docs though..

**Comment by anthonyorona** [comment]
The issue is what is noted in the docs, the server is not listening when the post request is executed. Here is my workaround:

    let server;
    beforeEach(async () => {
      server = createTestServer().listen(0, 'localhost');
      while (!server.listening) {
        // eslint-disable-next-line no-await-in-loop
        await new Promise(res => setTimeout(res, 250));
      }
      await (request(server).post('/auth/login').send({ email, password })).expect(200);
    });

**Comment by davidje13** [comment]
@anthonyorona your solution will work, but you can achieve the same a little cleaner by using _multiple_ `beforeEach` calls:

```javascript
let server;
beforeEach((done) => { // start server
  server = createTestServer();
  server.listen(0, 'localhost', done);
});

beforeEach(async () => { // log in
  await request(server).post('/auth/login').send({ email, password }).expect(200);
});
```

This is because `server.listen` sadly doesn't return a promise (it's a very old API), but Jest / Jasmine will recognise both callbacks and promises, just not in the same function. If you define multiple `beforeEach` hooks like this, they will run in the order you define them.
