### ISSUE TITLE
Newer supertest version support not released

### ISSUE THREAD

**Issue by alecgibson** [davidje13/superwstest#3]
Hi! Thanks for putting this library together! I see you've added support for newer supertest versions: https://github.com/davidje13/superwstest/commit/69a76dd60fd83a51778afdcb646f82a4da235705

But this isn't released in v1.1.0: https://github.com/davidje13/superwstest/blob/1.1.0/package.json#L42

Could we please get a release that adds this support?

**Comment by davidje13** [comment]
Sure; published as 1.1.1

:)
