### ISSUE TITLE
How do you set cookies?

### ISSUE THREAD

**Issue by alecgibson** [davidje13/superwstest#4]
In "normal" `supertest` you can set a cookie like so:

```js
request(app)
  .get('/')
  .set('Cookie', 'abc=xyz')
```

How do we do this in `superwstest`? I can't quite figure it out.

**Comment by alecgibson** [comment]
Aha got it:

```js
request(server)
  .ws('/path/to/ws', {headers: {cookie: 'abc=xyz'}})
```

**Comment by davidje13** [comment]
Adding an explicit API for this is an interesting idea (especially for parity with supertest's own API). I think it might be a little complex to implement, but I'll have a think.

Glad you found out how to do it (even though I forgot to document that extra parameters get passed directly to the `WebSocket` constructor of `ws`! I'll add some documentation for that…)

**Comment by davidje13** [comment]
Fixed up the documentation to hopefully be more useful and added your cookie setting example code.
