### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by thebigredgeek** [davidje13/superwstest#7]
Any plans for typescript support or definitions?

**Comment by davidje13** [comment]
TypeScript definitions are already provided: https://github.com/davidje13/superwstest/blob/master/index.d.ts

I'm using this in a few of my own TypeScript projects and it seems fine. Are you having problems with it?

**Comment by davidje13** [comment]
I'm going to close this since it seems to be invalid but if you want to provide additional details about what's not working for you, feel free to reopen it.
